(* S75B CELL *)
ClearAll["Global`*75B"];

expectedS75AProtocolHash75B=
"eeed82845625ea4f0a533ca5850eb3b236df58835dbb670ebcb973b7a0b311af";

expectedCandidatePool75B={1795,1,5,64,164,0};

s75AResultLock75B=And[
TrueQ[preflightPass75A],
TrueQ[cert75A["PreflightPassed"]],
TrueQ[cert75A["S75ResultLockPassed"]],
SameQ[protocolHash75A,expectedS75AProtocolHash75B],
SameQ[
Lookup[
cert75A["CandidatePoolSummary"],
{
"TrainingPerfectCandidates",
"S72PerfectCandidateCount",
"HeldAndLegacyPerfectCandidateCount",
"BestS72UnderHeldAndLegacyPerfect",
"MaximumSeenTotal",
"AllSeenPerfectCandidates"
}
],
expectedCandidatePool75B
],
SameQ[
Lookup[
cert75A["RepresentativeCandidates"],
"CandidateRole"
],
{
"FrozenProtocolSelection",
"BestCompatibleS72Perfect",
"HighestSeenTotal"
}
]
];

protocol75B=<|
"Stage"->"S75B",
"Name"->"CrossTopologySemanticAudit",
"AuditOnly"->True,
"CoreTCCTChanged"->False,
"OriginalFrozenModelChanged"->False,
"S75SelectionChanged"->False,
"S75AResultChanged"->False,
"AuditIntroducesNewCandidateSearch"->False,
"S75SearchReexecutedForStateReconstruction"->True,
"JointSemanticScopes"->{
"TrainingPlusHeldout",
"TrainingPlusLegacy",
"TrainingPlusS72",
"AllSeen"
},
"Distinguishes"->{
"TrainingCoverageGap",
"TrainContinueToValidationStop",
"TrainStopToValidationContinue",
"RawCrossTopologyObservationConflict",
"LatentCrossTopologySemanticConflict",
"TrainingPolicyAlignment"
},
"AblationTotalsRequireTrainingPerfect"->True,
"S75AResultLockPassed"->s75AResultLock75B
|>;

protocolHash75B=Hash[
Normal[protocol75B],
"SHA256",
"HexString"
];

preflightPass75B=And[
TrueQ[preflightPass75A],
TrueQ[s75AResultLock75B]
];

Dataset[{
Join[
protocol75B,
<|
"PreflightPassed"->preflightPass75B,
"S75AProtocolHash"->protocolHash75A,
"S75BProtocolHash"->protocolHash75B
|>
]
}]

(* S75B CELL *)
validationRows75B=Join[
heldRows75,
legacyValidationRows75,
s72ValidationRows75
];

allSeenRows75B=Join[
trainRows75,
validationRows75B
];

evaluationGroups75B=<|
"Heldout"->heldRows75,
"Legacy"->legacyValidationRows75,
"S72"->s72ValidationRows75,
"AllValidation"->validationRows75B
|>;

evaluationRowsByGrammar75B=AssociationMap[
Function[grammar,
Switch[
grammar,
"S59"|"ChainIn",
Select[
heldRows75,
# ["Grammar"]===grammar&
],
"SharedMerge"|"ParallelIn",
Select[
legacyValidationRows75,
# ["Grammar"]===grammar&
],
_,
Select[
s72ValidationRows75,
# ["Grammar"]===grammar&
]
]
],
grammarList75
];

dataCert75B=<|
"TrainingCases"->Length[trainRows75],
"HeldoutCases"->Length[heldRows75],
"LegacyCases"->Length[legacyValidationRows75],
"S72Cases"->Length[s72ValidationRows75],
"ValidationCases"->Length[validationRows75B],
"AllSeenCases"->Length[allSeenRows75B],
"CasesByGrammar"->Counts[Lookup[allSeenRows75B,"Grammar"]],
"TargetsByScope"->Association@KeyValueMap[
Function[{scope,rows},
scope->Counts[Lookup[rows,"Target"]]
],
Join[
<|"Training"->trainRows75|>,
evaluationGroups75B,
<|"AllSeen"->allSeenRows75B|>
]
]
|>;

Dataset[{dataCert75B}]

(* S75B CELL *)
ClearAll[
RawEncodedRows75B,
TokenSets75B,
TokenMeaning75B,
SemanticFeasibility75B,
PolicyErrorCounts75B,
CombinedAudit75B
];

RawEncodedRows75B[data_List]:=Map[
Function[row,
Join[
KeyTake[
row,
{"Grammar","Depth","Answer","Target"}
],
<|"Codes"->DeleteDuplicates[row["StatePairs"]]|>
]
],
data
];

TokenSets75B[encodedRows_List]:=Module[
{continueRows,stopRows,continueTokens,stopTokens},
continueRows=Select[
encodedRows,
# ["Target"]==="Continue"&
];
stopRows=Select[
encodedRows,
# ["Target"]==="Stop"&
];
continueTokens=If[
Length[continueRows]>0,
Union@@Lookup[continueRows,"Codes"],
{}
];
stopTokens=If[
Length[stopRows]>0,
Union@@Lookup[stopRows,"Codes"],
{}
];
<|
"Continue"->continueTokens,
"Stop"->stopTokens,
"ContinueOnly"->Complement[continueTokens,stopTokens],
"StopOnly"->Complement[stopTokens,continueTokens],
"Shared"->Intersection[continueTokens,stopTokens],
"All"->Union[continueTokens,stopTokens]
|>
];

TokenMeaning75B[
token_,
sets_Association
]:=Switch[
{
MemberQ[sets["Continue"],token],
MemberQ[sets["Stop"],token]
},
{True,False},"Continue",
{False,True},"Stop",
{True,True},"Mixed",
_,"Absent"
];

SemanticFeasibility75B[
encodedRows_List
]:=Module[{sets,safePolicy,safeScore},
sets=TokenSets75B[encodedRows];
safePolicy=sets["ContinueOnly"];
safeScore=ScoreEncoded75[
encodedRows,
safePolicy
];
<|
"Cases"->Length[encodedRows],
"DistinctTokens"->Length[sets["All"]],
"SharedTokens"->Length[sets["Shared"]],
"SafePolicy"->safePolicy,
"SafeSemanticPolicyScore"->safeScore,
"PerfectPurePolicyFeasible"->SameQ[
safeScore,
Length[encodedRows]
]
|>
];

PolicyErrorCounts75B[
encodedRows_List,
policy_List
]:=Module[{missedContinue,triggeredStop},
missedContinue=Count[
encodedRows,
row_/;And[
row["Target"]==="Continue",
Not@AnyTrue[
row["Codes"],
MemberQ[policy,#]&
]
]
];
triggeredStop=Count[
encodedRows,
row_/;And[
row["Target"]==="Stop",
AnyTrue[
row["Codes"],
MemberQ[policy,#]&
]
]
];
<|
"MissedContinueCases"->missedContinue,
"TriggeredStopCases"->triggeredStop
|>
];

CombinedAudit75B[
spec_Association,
evaluationLabel_String,
evaluationRows_List
]:=Module[
{
candidate,trainLatent,evaluationLatent,combinedLatent,
combinedRaw,trainSets,evaluationSets,combinedSets,
rawFeasibility,latentFeasibility,policyScoreEvaluation,
policyScoreCombined,policyErrors,continueToStop,stopToContinue,
unseenContinue,unseenStop,blockedContinue,rootCause
},
candidate=spec["Candidate"];
trainLatent=EncodeRows75[
trainRows75,
candidate["Params"],
candidate["K"]
];
evaluationLatent=EncodeRows75[
evaluationRows,
candidate["Params"],
candidate["K"]
];
combinedLatent=Join[
trainLatent,
evaluationLatent
];
combinedRaw=RawEncodedRows75B[
Join[trainRows75,evaluationRows]
];
trainSets=TokenSets75B[trainLatent];
evaluationSets=TokenSets75B[evaluationLatent];
combinedSets=TokenSets75B[combinedLatent];
rawFeasibility=SemanticFeasibility75B[combinedRaw];
latentFeasibility=SemanticFeasibility75B[combinedLatent];
policyScoreEvaluation=ScoreEncoded75[
evaluationLatent,
candidate["Policy"]
];
policyScoreCombined=ScoreEncoded75[
combinedLatent,
candidate["Policy"]
];
policyErrors=PolicyErrorCounts75B[
evaluationLatent,
candidate["Policy"]
];
continueToStop=Intersection[
trainSets["ContinueOnly"],
evaluationSets["Stop"]
];
stopToContinue=Intersection[
trainSets["Stop"],
evaluationSets["Continue"]
];
unseenContinue=Complement[
evaluationSets["Continue"],
trainSets["All"]
];
unseenStop=Complement[
evaluationSets["Stop"],
trainSets["All"]
];
blockedContinue=Intersection[
evaluationSets["Continue"],
trainSets["Stop"]
];
rootCause=Which[
Not@TrueQ[rawFeasibility["PerfectPurePolicyFeasible"]],
"RawCrossTopologyObservationConflict",
Not@TrueQ[latentFeasibility["PerfectPurePolicyFeasible"]],
"LatentCrossTopologySemanticConflict",
policyScoreCombined==Length[combinedLatent],
"None",
And[
Length[continueToStop]>0,
Length[unseenContinue]>0
],
"PolicySemanticFlipAndCoverageGap",
Length[continueToStop]>0,
"TrainingContinueToValidationStopFlip",
Length[blockedContinue]>0,
"TrainingStopToValidationContinueFlip",
Length[unseenContinue]>0,
"TrainingCoverageGap",
True,
"TrainingPolicyAlignmentOther"
];
Join[
<|
"CandidateRole"->spec["CandidateRole"],
"EvaluationScope"->evaluationLabel,
"EvaluationCases"->Length[evaluationRows],
"CombinedCases"->Length[combinedLatent],
"RawSharedTokensCombined"->rawFeasibility["SharedTokens"],
"RawSafePolicyScoreCombined"->rawFeasibility[
"SafeSemanticPolicyScore"
],
"RawPerfectPolicyFeasible"->rawFeasibility[
"PerfectPurePolicyFeasible"
],
"LatentSharedTokensCombined"->latentFeasibility["SharedTokens"],
"LatentSafePolicyScoreCombined"->latentFeasibility[
"SafeSemanticPolicyScore"
],
"LatentPerfectPolicyFeasible"->latentFeasibility[
"PerfectPurePolicyFeasible"
],
"TrainingPolicyScoreEvaluation"->policyScoreEvaluation,
"TrainingPolicyScoreCombined"->policyScoreCombined,
"TrainContinueToEvaluationStopTokens"->Length[continueToStop],
"TrainStopToEvaluationContinueTokens"->Length[stopToContinue],
"EvaluationContinueTokensBlockedByTrainStop"->Length[
blockedContinue
],
"UnseenEvaluationContinueTokens"->Length[unseenContinue],
"UnseenEvaluationStopTokens"->Length[unseenStop],
"RootCause"->rootCause
|>,
policyErrors
]
];

(* S75B CELL *)
combinedAuditRows75B=Flatten[
Table[
KeyValueMap[
Function[{label,rows},
CombinedAudit75B[spec,label,rows]
],
evaluationGroups75B
],
{spec,representativeSpecs75A}
],
1
];

Dataset[combinedAuditRows75B]

grammarCrossAuditRows75B=Flatten[
Table[
Map[
Function[grammar,
CombinedAudit75B[
spec,
grammar,
evaluationRowsByGrammar75B[grammar]
]
],
grammarList75
],
{spec,representativeSpecs75A}
],
1
];

Dataset[grammarCrossAuditRows75B]

(* S75B CELL *)
ClearAll[
TokenIssueLabels75B,
TokenProvenanceRows75B
];

TokenIssueLabels75B[
trainMeaning_String,
validationMeaning_String,
allSeenMeaning_String
]:=DeleteCases[
{
If[
And[
trainMeaning==="Continue",
MemberQ[{"Stop","Mixed"},validationMeaning]
],
"TrainContinueToValidationStop",
Nothing
],
If[
And[
trainMeaning==="Stop",
MemberQ[{"Continue","Mixed"},validationMeaning]
],
"TrainStopToValidationContinue",
Nothing
],
If[
And[
trainMeaning==="Absent",
MemberQ[{"Continue","Mixed"},validationMeaning]
],
"UnseenValidationContinue",
Nothing
],
If[
And[
trainMeaning==="Absent",
MemberQ[{"Stop","Mixed"},validationMeaning]
],
"UnseenValidationStop",
Nothing
],
If[
allSeenMeaning==="Mixed",
"GloballyMixedMeaning",
Nothing
]
},
Nothing
];

TokenProvenanceRows75B[
spec_Association
]:=Module[
{
candidate,trainEncoded,heldEncoded,legacyEncoded,s72Encoded,
validationEncoded,allSeenEncoded,trainSets,heldSets,legacySets,
s72Sets,validationSets,allSeenSets,grammarSets,observedTokens
},
candidate=spec["Candidate"];
trainEncoded=EncodeRows75[
trainRows75,candidate["Params"],candidate["K"]
];
heldEncoded=EncodeRows75[
heldRows75,candidate["Params"],candidate["K"]
];
legacyEncoded=EncodeRows75[
legacyValidationRows75,candidate["Params"],candidate["K"]
];
s72Encoded=EncodeRows75[
s72ValidationRows75,candidate["Params"],candidate["K"]
];
validationEncoded=Join[
heldEncoded,legacyEncoded,s72Encoded
];
allSeenEncoded=Join[
trainEncoded,validationEncoded
];
trainSets=TokenSets75B[trainEncoded];
heldSets=TokenSets75B[heldEncoded];
legacySets=TokenSets75B[legacyEncoded];
s72Sets=TokenSets75B[s72Encoded];
validationSets=TokenSets75B[validationEncoded];
allSeenSets=TokenSets75B[allSeenEncoded];
grammarSets=AssociationMap[
Function[grammar,
TokenSets75B@EncodeRows75[
fullRowsByGrammar75[grammar],
candidate["Params"],
candidate["K"]
]
],
grammarList75
];
observedTokens=allSeenSets["All"];
Map[
Function[token,
Module[
{trainMeaning,validationMeaning,allSeenMeaning},
trainMeaning=TokenMeaning75B[token,trainSets];
validationMeaning=TokenMeaning75B[token,validationSets];
allSeenMeaning=TokenMeaning75B[token,allSeenSets];
<|
"CandidateRole"->spec["CandidateRole"],
"Token"->token,
"SelectedByTrainingPolicy"->MemberQ[
candidate["Policy"],
token
],
"TrainingMeaning"->trainMeaning,
"HeldoutMeaning"->TokenMeaning75B[token,heldSets],
"LegacyMeaning"->TokenMeaning75B[token,legacySets],
"S72Meaning"->TokenMeaning75B[token,s72Sets],
"ValidationMeaning"->validationMeaning,
"AllSeenMeaning"->allSeenMeaning,
"GrammarMeanings"->AssociationMap[
TokenMeaning75B[token,grammarSets[#]]&,
grammarList75
],
"IssueLabels"->TokenIssueLabels75B[
trainMeaning,
validationMeaning,
allSeenMeaning
]
|>
]
],
observedTokens
]
];

allTokenProvenanceRows75B=Flatten[
TokenProvenanceRows75B/@representativeSpecs75A,
1
];

tokenIssueRows75B=Select[
allTokenProvenanceRows75B,
Length[# ["IssueLabels"]]>0&
];

Dataset[tokenIssueRows75B]

(* S75B CELL *)
correctedAblationRows75B=Map[
Function[row,
Join[
KeyDrop[row,{"SeenTotal"}],
<|
"ValidationTotal"->row["SeenTotal"],
"ProtocolEligible"->TrueQ[row["TrainPerfect"]],
"EligibleValidationTotal"->If[
TrueQ[row["TrainPerfect"]],
row["SeenTotal"],
Missing["TrainingNotPerfect"]
],
"AblationScope"->"LocalFixedParameterDiagnostic"
|>
]
],
ablationRows75A
];

Dataset[correctedAblationRows75B]

eligibleAblationSummary75B=Map[
Function[role,
Module[{eligible,bestScore,bestRows},
eligible=Select[
correctedAblationRows75B,
And[
# ["CandidateRole"]===role,
TrueQ[# ["ProtocolEligible"]]
]&
];
bestScore=If[
Length[eligible]>0,
Max[Lookup[eligible,"EligibleValidationTotal"]],
Missing["NoEligibleAblation"]
];
bestRows=If[
MissingQ[bestScore],
{},
Select[
eligible,
# ["EligibleValidationTotal"]===bestScore&
]
];
<|
"CandidateRole"->role,
"EligibleAblations"->Length[eligible],
"BestEligibleValidationTotal"->bestScore,
"BestEligibleModes"->Lookup[bestRows,"Ablation"]
|>
]
],
Lookup[representativeSpecs75A,"CandidateRole"]
];

Dataset[eligibleAblationSummary75B]

(* S75B CELL *)
globalAuditRows75B=Select[
combinedAuditRows75B,
# ["EvaluationScope"]==="AllValidation"&
];

tokenIssueCountsByRole75B=Map[
Function[role,
<|
"CandidateRole"->role,
"IssueCounts"->Counts@Flatten@Lookup[
Select[
tokenIssueRows75B,
# ["CandidateRole"]===role&
],
"IssueLabels"
]
|>
],
Lookup[representativeSpecs75A,"CandidateRole"]
];

globalCrossTopologySummary75B=Map[
KeyTake[
#,
{
"CandidateRole",
"RawPerfectPolicyFeasible",
"LatentPerfectPolicyFeasible",
"RawSafePolicyScoreCombined",
"LatentSafePolicyScoreCombined",
"TrainingPolicyScoreCombined",
"TrainContinueToEvaluationStopTokens",
"TrainStopToEvaluationContinueTokens",
"EvaluationContinueTokensBlockedByTrainStop",
"UnseenEvaluationContinueTokens",
"UnseenEvaluationStopTokens",
"MissedContinueCases",
"TriggeredStopCases",
"RootCause"
}
]&,
globalAuditRows75B
];

cert75B=<|
"Stage"->"S75B",
"Name"->"CrossTopologySemanticAudit",
"AuditOnly"->True,
"CoreTCCTChanged"->False,
"OriginalFrozenModelChanged"->False,
"S75SelectionChanged"->False,
"S75AResultChanged"->False,
"S75AResultLockPassed"->s75AResultLock75B,
"PreflightPassed"->preflightPass75B,
"S75AProtocolHash"->protocolHash75A,
"S75BProtocolHash"->protocolHash75B,
"DataCertificate"->dataCert75B,
"GlobalCrossTopologySummary"->globalCrossTopologySummary75B,
"TokenIssueCountsByRole"->tokenIssueCountsByRole75B,
"AblationComparisonCorrected"->True,
"AblationsAreLocalFixedParameterDiagnostics"->True,
"NewCandidateSearchIntroduced"->False,
"S76BlindTestRun"->False
|>;

Dataset[{cert75B}]
